# Using Makefile to be able to run single 'build' command in Eclipse'
# Create build folder, change dir to it and create cmake files from CMakeLists.txt
# Then run make in build folder
all:
	mkdir build; cd build && cmake ../ && make
clean:
	cd build && make clean
